In [1]:
import pandas as pd 
import numpy as np

In [2]:
np.random.seed(42)

In [3]:
mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

In [4]:
df

    feature1  feature2  feature3  target
0   0.496714 -0.138264  0.647689       1
1   1.523030 -0.234153 -0.234137       1
2   1.579213  0.767435 -0.469474       1
3   0.542560 -0.463418 -0.465730       1
4   0.241962 -1.913280 -1.724918       1
5  -0.562288 -1.012831  0.314247       1
6  -0.908024 -1.412304  1.465649       1
7  -0.225776  0.067528 -1.424748       1
8  -0.544383  0.110923 -1.150994       1
9   0.375698 -0.600639 -0.291694       1
10 -0.601707  1.852278 -0.013497       1
11 -1.057711  0.822545 -1.220844       1
12  0.208864 -1.959670 -1.328186       1
13  0.196861  0.738467  0.171368       1
14 -0.115648 -0.301104 -1.478522       1
15 -0.719844 -0.460639  1.057122       1
16  0.343618 -1.763040  0.324084       1
17 -0.385082 -0.676922  0.611676       1
18  1.031000  0.931280 -0.839218       1
19 -0.309212  0.331263  0.975545       1

In [5]:
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

In [6]:
df1

    feature1  feature2  feature3  target
0   0.520826  0.814341 -0.106335       0
1  -0.196207  1.812526  2.356240       0
2   0.927990  2.003533  1.361636       0
3   0.354880  1.361396  2.538037       0
4   0.964174  2.564644 -1.619745       0
5   1.821903  1.087047  0.700993       0
6   1.091761 -0.987569  0.780328       0
7   1.357113  2.477894  0.481730       0
8   0.191506  0.498243  1.915402       0
9   1.328751  0.470240  1.513267       0
10  1.097078  1.968645  0.297947       0
11  0.672338  0.607892 -0.463515       0
12  1.296120  1.261055  1.005113       0
13  0.765413 -0.415371  0.579355       0
14  0.657285  0.197723  0.838714       0
15  1.404051  2.886186  1.174578       0
16  1.257550  0.925554 -0.918771       0
17  0.973486  1.060230  3.463242       0
18  0.807639  1.301547  0.965288       0
19 -0.168678  2.142823  1.751933       0

In [7]:
df = pd.concat([df, df1], ignore_index=True)
df = df.sample(40)

In [8]:
df

    feature1  feature2  feature3  target
32  1.296120  1.261055  1.005113       0
36  1.257550  0.925554 -0.918771       0
35  1.404051  2.886186  1.174578       0
22  0.927990  2.003533  1.361636       0
11 -1.057711  0.822545 -1.220844       1
25  1.821903  1.087047  0.700993       0
13  0.196861  0.738467  0.171368       1
12  0.208864 -1.959670 -1.328186       1
9   0.375698 -0.600639 -0.291694       1
39 -0.168678  2.142823  1.751933       0
24  0.964174  2.564644 -1.619745       0
14 -0.115648 -0.301104 -1.478522       1
1   1.523030 -0.234153 -0.234137       1
17 -0.385082 -0.676922  0.611676       1
7  -0.225776  0.067528 -1.424748       1
28  0.191506  0.498243  1.915402       0
27  1.357113  2.477894  0.481730       0
6  -0.908024 -1.412304  1.465649       1
20  0.520826  0.814341 -0.106335       0
38  0.807639  1.301547  0.965288       0
18  1.031000  0.931280 -0.839218       1
3   0.542560 -0.463418 -0.465730       1
19 -0.309212  0.331263  0.975545       1
2   1.579213  0.767435 -0.469474       1
29  1.328751  0.470240  1.513267       0
34  0.657285  0.197723  0.838714       0
26  1.091761 -0.987569  0.780328       0
8  -0.544383  0.110923 -1.150994       1
0   0.496714 -0.138264  0.647689       1
31  0.672338  0.607892 -0.463515       0
15 -0.719844 -0.460639  1.057122       1
30  1.097078  1.968645  0.297947       0
10 -0.601707  1.852278 -0.013497       1
21 -0.196207  1.812526  2.356240       0
5  -0.562288 -1.012831  0.314247       1
33  0.765413 -0.415371  0.579355       0
4   0.241962 -1.913280 -1.724918       1
23  0.354880  1.361396  2.538037       0
37  0.973486  1.060230  3.463242       0
16  0.343618 -1.763040  0.324084       1

In [9]:
import plotly.express as px

fig = px.scatter_3d(
    df,
    x='feature1',
    y='feature2',
    z='feature3',
    color='target',
    symbol='target',
    title='3D Scatter Plot of Features',
    opacity=0.8
)
fig.show()

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [11]:
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.35175    0.07987862]
 [0.35175    1.02564103 0.28328008]
 [0.07987862 0.28328008 1.02564103]]

In [12]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [13]:
eigen_values

array([1.51825759, 0.94771609, 0.6109494 ])

In [14]:
eigen_vectors

array([[-0.56014874, -0.62132881,  0.5478904 ],
       [-0.67561935, -0.04005698, -0.73616162],
       [-0.47934526,  0.78252536,  0.3973439 ]])